import type { types } from "@tsdl/core";

export default {
  mwDoc: [],
  path: ["TSDL"],
  leaf: false,
  nodes: [
    {
      mwDoc: [],
      path: ["TSDL", "highSchool"],
      leaf: false,
      nodes: [
        {
          mwDoc: [],
          path: ["TSDL", "highSchool", "sections"],
          leaf: false,
          nodes: [
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "school"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: "Test", description: "test description" },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "images"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "programs"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "socialMedia"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "characteristics"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "organization"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "notice"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "practical"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "questions"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "events"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "educationStats"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "studentOpinion"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "studentInformation"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "afterHighSchool"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "acceptPolicyText"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "sections", "similarSchools"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
          ],
        },
        {
          mwDoc: [],
          path: ["TSDL", "highSchool", "projections"],
          leaf: false,
          nodes: [
            {
              mwDoc: [{ name: null, description: null }],
              path: ["TSDL", "highSchool", "projections", "allSchools"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "projections", "allPaths"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
          ],
        },
        {
          mwDoc: [],
          path: ["TSDL", "highSchool", "collections"],
          leaf: false,
          nodes: [
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "collections", "popular"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: [
                "TSDL",
                "highSchool",
                "collections",
                "searchProjectPrograms",
              ],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: [
                "TSDL",
                "highSchool",
                "collections",
                "searchProjectStatistics",
              ],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [{ name: null, description: null }],
              path: [
                "TSDL",
                "highSchool",
                "collections",
                "searchProjectMobile",
              ],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
          ],
        },
        {
          mwDoc: [],
          path: ["TSDL", "highSchool", "actions"],
          leaf: false,
          nodes: [
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "actions", "askQuestion"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
          ],
        },
        {
          mwDoc: [],
          path: ["TSDL", "highSchool", "misc"],
          leaf: false,
          nodes: [
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "misc", "slugToId"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "misc", "availableMunicipalities"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "misc", "getCityFromCoords"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: [
                "TSDL",
                "highSchool",
                "misc",
                "searchAvailableMunicipalities",
              ],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "misc", "admissionPointSpread"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "misc", "hasRanking"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: ["TSDL", "highSchool", "misc", "municipality"],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
            {
              mwDoc: [],
              path: [
                "TSDL",
                "highSchool",
                "misc",
                "parentMunicipalityHomogenous",
              ],
              leaf: true,
              inputDoc: { name: null, description: null },
              queryDoc: { name: null, description: null },
              nodes: [],
            },
          ],
        },
      ],
    },
  ],
} satisfies types.tree.Tree;
