export declare const errorCodes: {
  readonly "Bad Request": 400;
  readonly Unauthorized: 401;
  readonly "Payment Required": 402;
  readonly Forbidden: 403;
  readonly "Not Found": 404;
  readonly "Method Not Allowed": 405;
  readonly "Not Acceptable": 406;
  readonly "Proxy Authentication Required": 407;
  readonly "Request Timeout": 408;
  readonly Conflict: 409;
  readonly Gone: 410;
  readonly "Length Required": 411;
  readonly "Precondition Failed": 412;
  readonly "Payload Too Large": 413;
  readonly "URI Too Long": 414;
  readonly "Unsupported Media Type": 415;
  readonly "Range Not Satisfiable": 416;
  readonly "Expectation Failed": 417;
  readonly "I'm a teapot": 418;
  readonly "Misdirected Request": 421;
  readonly "Unprocessable Content": 422;
  readonly Locked: 423;
  readonly "Failed Dependency": 424;
  readonly "Too Early": 425;
  readonly "Upgrade Required": 426;
  readonly "Precondition Required": 428;
  readonly "Too Many Requests": 429;
  readonly "Request Header Fields Too Large": 431;
  readonly "Unavailable For Legal Reasons": 451;
  readonly "Internal Server Error": 500;
  readonly "Not Implemented": 501;
  readonly "Bad Gateway": 502;
  readonly "Service Unavailable": 503;
  readonly "Gateway Timeout": 504;
  readonly "HTTP Version Not Supported": 505;
  readonly "Variant Also Negotiates": 506;
  readonly "Insufficient Storage": 507;
  readonly "Loop Detected": 508;
  readonly "Not Extended": 510;
  readonly "Network Authentication Required": 511;
};
